name: Release

on:
  release:
    types: [published]

jobs:
  publish-github-package:
    name: Publish GitHub Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: npm publish --registry=https://npm.pkg.github.com
